pipeline {
    agent any
    
    environment {
        PATH = "$PATH:/var/lib/jenkins/.local/bin"
        AWS_SAM_STACK_NAME = "Jenkins-Lambda"
        AWS_REGION = 'us-east-1' 
    }
    stages {
        stage('Setup') {
            steps {
                sh "pip3 install -r Jenkins-Lambda/tests/requirements.txt"
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
            }
        }
        stage('Build') {
            steps {
                sh "sam build -t Jenkins-Lambda/template.yaml"
            }
        }
        //Deploy needs credentials of AWS, which are stored in Jenkin credentials
        stage('Deploy') {
            environment {
                //names should according to the documentation i.e, AWS_ACCESS_KEY_ID
                AWS_ACCESS_KEY_ID = credentials('aws-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
            }
            steps{
                sh "sam deploy -t Jenkins-Lambda/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset"
            }
        }
    }
}